"""crear tabla usuarios

Revision ID: 05a68b76b046
Revises: d9dc9fa872ea
Create Date: 2026-07-01 23:20:41.964699

"""
from alembic import op
import sqlalchemy as sa


# identificadores usados por Alembic
revision = '05a68b76b046'
down_revision = 'd9dc9fa872ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_usuario'), 'usuarios', ['usuario'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_usuario'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
