"""agregar campos de historia clinica a paciente

Revision ID: 0715d5eebc49
Revises: 05a68b76b046
Create Date: 2026-07-02 23:51:30.994135

"""
from alembic import op
import sqlalchemy as sa


# identificadores usados por Alembic
revision = '0715d5eebc49'
down_revision = '05a68b76b046'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacientes', sa.Column('razon_consulta', sa.Text(), nullable=True))
    op.add_column('pacientes', sa.Column('historia_clinica_familiar', sa.Text(), nullable=True))
    op.add_column('pacientes', sa.Column('historia_clinica_pasada', sa.Text(), nullable=True))
    op.add_column('pacientes', sa.Column('antecedentes_previos', sa.Text(), nullable=True))
    op.add_column('pacientes', sa.Column('estudios_previos', sa.Text(), nullable=True))
    op.add_column('pacientes', sa.Column('medicamentos', sa.Text(), nullable=True))
    op.add_column('pacientes', sa.Column('otros_datos', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pacientes', 'otros_datos')
    op.drop_column('pacientes', 'medicamentos')
    op.drop_column('pacientes', 'estudios_previos')
    op.drop_column('pacientes', 'antecedentes_previos')
    op.drop_column('pacientes', 'historia_clinica_pasada')
    op.drop_column('pacientes', 'historia_clinica_familiar')
    op.drop_column('pacientes', 'razon_consulta')
    # ### end Alembic commands ###
