"""agregar tabla seguimientos

Revision ID: 36ddf9950864
Revises: cfa24a7b0fbd
Create Date: 2026-07-20 11:54:56.816192

"""
from alembic import op
import sqlalchemy as sa


# identificadores usados por Alembic
revision = '36ddf9950864'
down_revision = 'cfa24a7b0fbd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
