"""agregar examen fisico y diagrama corporal a paciente

Revision ID: 412b374bd077
Revises: 0715d5eebc49
Create Date: 2026-07-04 11:27:11.439300

"""
from alembic import op
import sqlalchemy as sa


# identificadores usados por Alembic
revision = '412b374bd077'
down_revision = '0715d5eebc49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacientes', sa.Column('leg_check', sa.Text(), nullable=True))
    op.add_column('pacientes', sa.Column('nervoscope', sa.Text(), nullable=True))
    op.add_column('pacientes', sa.Column('visualizacion_frente', sa.Text(), nullable=True))
    op.add_column('pacientes', sa.Column('visualizacion_perfil', sa.Text(), nullable=True))
    op.add_column('pacientes', sa.Column('palpacion_estatica', sa.Text(), nullable=True))
    op.add_column('pacientes', sa.Column('palpacion_dinamica', sa.Text(), nullable=True))
    op.add_column('pacientes', sa.Column('radiografia', sa.Text(), nullable=True))
    op.add_column('pacientes', sa.Column('diagrama_corporal', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pacientes', 'diagrama_corporal')
    op.drop_column('pacientes', 'radiografia')
    op.drop_column('pacientes', 'palpacion_dinamica')
    op.drop_column('pacientes', 'palpacion_estatica')
    op.drop_column('pacientes', 'visualizacion_perfil')
    op.drop_column('pacientes', 'visualizacion_frente')
    op.drop_column('pacientes', 'nervoscope')
    op.drop_column('pacientes', 'leg_check')
    # ### end Alembic commands ###
