"""eliminar columna diagrama_corporal de pacientes

Revision ID: 4dfff639aa97
Revises: b901e7dd2c3b
Create Date: 2026-07-27 19:34:17.004390

"""
from alembic import op
import sqlalchemy as sa


# identificadores usados por Alembic
revision = '4dfff639aa97'
down_revision = 'b901e7dd2c3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pacientes', 'diagrama_corporal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacientes', sa.Column('diagrama_corporal', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
