"""agregar tabla radiografias faltante

Revision ID: 8719db66c904
Revises: 9703e920304e
Create Date: 2026-07-05 15:46:40.612820

"""
from alembic import op
import sqlalchemy as sa


# identificadores usados por Alembic
revision = '8719db66c904'
down_revision = '9703e920304e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radiografias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=500), nullable=False),
    sa.Column('tipo_archivo', sa.String(length=100), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_radiografias_paciente_id'), 'radiografias', ['paciente_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_radiografias_paciente_id'), table_name='radiografias')
    op.drop_table('radiografias')
    # ### end Alembic commands ###
