"""crear tabla radiografias y sacar radiografia de paciente

Revision ID: 9703e920304e
Revises: a8516243b68a
Create Date: 2026-07-05 15:40:59.765627

"""
from alembic import op
import sqlalchemy as sa


# identificadores usados por Alembic
revision = '9703e920304e'
down_revision = 'a8516243b68a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
