"""crear tabla radiografias y sacar radiografia de paciente

Revision ID: a8516243b68a
Revises: 412b374bd077
Create Date: 2026-07-04 12:08:36.223072

"""
from alembic import op
import sqlalchemy as sa


# identificadores usados por Alembic
revision = 'a8516243b68a'
down_revision = '412b374bd077'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pacientes', 'radiografia')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacientes', sa.Column('radiografia', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
