"""agregar diagrama_corporal_ruta a pacientes

Revision ID: b901e7dd2c3b
Revises: dcca3e3bb3dc
Create Date: 2026-07-27 16:27:24.614575

"""
from alembic import op
import sqlalchemy as sa


# identificadores usados por Alembic
revision = 'b901e7dd2c3b'
down_revision = 'dcca3e3bb3dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacientes', sa.Column('diagrama_corporal_ruta', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pacientes', 'diagrama_corporal_ruta')
    # ### end Alembic commands ###
