"""agregar examen de hemisfericidad a paciente

Revision ID: cfa24a7b0fbd
Revises: 8719db66c904
Create Date: 2026-07-19 21:21:03.127913

"""
from alembic import op
import sqlalchemy as sa


# identificadores usados por Alembic
revision = 'cfa24a7b0fbd'
down_revision = '8719db66c904'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacientes', sa.Column('hemisfericidad_examen', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pacientes', 'hemisfericidad_examen')
    # ### end Alembic commands ###
