"""crear tabla pacientes

Revision ID: d9dc9fa872ea
Revises: 
Create Date: 2026-07-01 16:51:00.369646

"""
from alembic import op
import sqlalchemy as sa


# identificadores usados por Alembic
revision = 'd9dc9fa872ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dni', sa.String(length=15), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('ocupacion', sa.String(length=150), nullable=True),
    sa.Column('recomendado', sa.String(length=150), nullable=True),
    sa.Column('actividad_fisica', sa.String(length=200), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pacientes_dni'), 'pacientes', ['dni'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pacientes_dni'), table_name='pacientes')
    op.drop_table('pacientes')
    # ### end Alembic commands ###
