"""agregar hemisfericidad_resultado_guardado a paciente

Revision ID: dcca3e3bb3dc
Revises: 36ddf9950864
Create Date: 2026-07-20 12:11:57.450168

"""
from alembic import op
import sqlalchemy as sa


# identificadores usados por Alembic
revision = 'dcca3e3bb3dc'
down_revision = '36ddf9950864'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacientes', sa.Column('hemisfericidad_resultado_guardado', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pacientes', 'hemisfericidad_resultado_guardado')
    # ### end Alembic commands ###
